# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0b1c567bbd9a81732b67dac5dc23dfcfa6e35707634d036e48dff821d67379102d6439dc71855d69cf0c239ce6b1c265f22f607618bdca5eb37e6bb8f706cb

test:
  secret_key_base: f0280b0ac7034507c2bdeff1bfb6022b66820b40b434116318b97450ed4c1236cbf053a74d5d635dbae4303155b03bb8edb7b1763231b546ec026003b07d20e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
